name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8]
        django-version: [django21, django22, django30, django31]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox coverage

    - name: Create tox.ini
      run: |
        echo "[tox]" > tox.ini
        echo "envlist = py38-django21, py38-django22, py38-django30, py38-django31" >> tox.ini
        echo "[testenv]" >> tox.ini
        echo "deps =" >> tox.ini
        echo "    django21: Django>=2.1,<2.2" >> tox.ini
        echo "    django22: Django>=2.2,<2.3" >> tox.ini
        echo "    django30: Django>=3.0,<3.1" >> tox.ini
        echo "    django31: Django>=3.1,<3.2" >> tox.ini
        echo "commands = python manage.py test" >> tox.ini

    - name: Run tests
      env:
        TOX_ENV: py${{ matrix.python-version[0] }}${{ matrix.python-version[2] }}-${{ matrix.django-version }}
      run: |
        tox -r -e $TOX_ENV

    - name: Upload coverage to Codecov
      if: success()
      run: |
        bash <(curl -s https://codecov.io/bash)
